baseURL = 'https://flooow.github.io/blog'
languageCode = 'en-us'
title = 'Ace of rebase'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

  [params.ananke_socials.mastodon]
  name = "mastodon"
  url = "https://mamot.fr/@Flow"
  rel = "me noopener"

  [params.ananke_socials.github]
  name = "github"
  url = "https://github.com/FloooW"

  [params.ananke_social.linkedin]
  name = "linkedin"
  url = "https://www.linkedin.com/in/florentlerat/"