baseURL = 'https://flooow.github.io/blog'
languageCode = 'en-us'
title = 'Ace of rebase'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-yellow"
  recent_posts_number = 3

[[params.ananke_socials]]
name: mastodon
url: https://mamot.fr/@Flow
rel: me noopener